<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 3 (http://www.altova.com) by R. Howe (NC3A The Hague) -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:nvgwsdl="http://tide.act.nato.int/wsdl/nvg" xmlns:tns="urn:int:nato:nc3a:demo:nvg" xmlns:nvgwsdl09="http://tide.act.nato.int/wsdl/2009/nvg" xmlns:ns="http://purl.org/dc/elements/1.1/" xmlns:ns1="http://purl.org/dc/terms/" xmlns:ns2="http://tide.act.nato.int/schemas/2009/10/streaming/nvg" xmlns:ns3="http://tide.act.nato.int/schemas/2008/10/nvg" xmlns:ns4="http://tide.act.nato.int/schemas/2009/10/nvg" xmlns:ns5="http://purl.org/dc/dcmitype/" name="NVG-NC3A-Demo" targetNamespace="urn:int:nato:nc3a:demo:nvg">
	<wsdl:import namespace="http://tide.act.nato.int/wsdl/2009/nvg" location="nvg2009.wsdl"/>
	<wsdl:types/>
	<wsdl:binding name="NVGBinding2009" type="nvgwsdl09:NVGPortType2009">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="GetCapabilities">
			<soap:operation soapAction="urn:#GetCapabilities:2009"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="GetNvg">
			<soap:operation soapAction="urn:#GetNvg:2009"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="NvgService">
		<wsdl:port name="NvgPort15" binding="tns:NVGBinding2009">
			<soap:address location="http://localhost/nvg2009"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
