<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
xmlns:tns="urn:int:nato:nc3a:demo:nvg"
xmlns:nvgwsdl="http://tide.act.nato.int/wsdl/nvg"
xmlns:nvgwsdl09="http://tide.act.nato.int/wsdl/2009/nvg"
xmlns:ns2="http://tide.act.nato.int/schemas/2009/10/nvg/streaming"
name="NVG-NC3A-Demo" targetNamespace="urn:int:nato:nc3a:demo:nvg">
	<wsdl:import namespace="http://tide.act.nato.int/wsdl/2009/nvg" location="nvg2009.wsdl"/>
	<wsdl:import namespace="http://tide.act.nato.int/schemas/2009/10/nvg/streaming" location="nvg.streaming.sub.1.5.wsdl"/>
	<wsdl:types/>
	<wsdl:binding name="NVG15Binding" type="nvgwsdl09:NVGPortType2009">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="GetCapabilities">
			<soap:operation soapAction="urn:#GetCapabilities:2009"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="GetNvg">
			<soap:operation soapAction="urn:#GetNvg:2009"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:binding name="Nvg15PubSubBinding" type="ns2:SubscriptionProducerPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="Subscribe">
			<soap:operation soapAction="urn:#Subscribe"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="Cancel">
			<soap:operation soapAction="urn:#Cancel"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:binding name="Nvg15SubBinding" type="ns2:SubscriptionConsumerPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="SendMessage">
			<soap:operation soapAction="urn:#SendMessage"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="NvgService">
		<wsdl:port name="NvgPort15" binding="tns:NVG15Binding">
			<soap:address location="http://localhost/nvg2009"/>
		</wsdl:port>
		<wsdl:port name="Pubsub15" binding="tns:Nvg15PubSubBinding">
			<soap:address location="http://localhost/pub15"/>
		</wsdl:port>
	</wsdl:service>
	<wsdl:service name="NvgSubConsumerService">
		<wsdl:port name="Sub15" binding="tns:Nvg15SubBinding">
			<soap:address location="http://localhost/sub15"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
